name: finplan24
description: Приложение по учету финансов
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  uuid: ^4.3.3
  rxdart: ^0.27.5
  realm: ^1.6.1
  auto_route: ^7.8.4
  csv: ^5.1.1
  file_picker: ^3.0.0
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  generate: true
